POST http://localhost/api/DataLog

{
  "content": "string",
  "openid": "string",
  "page": "string"
}

###

POST http://localhost/api/BehaviorLog

{
  "control": "string",
  "openid": "string",
  "page": "string"
}

###

GET http://localhost/api/BehaviorLog/csv

###

POST http://localhost/api/feedback

{
  "contactInfo": "string",
  "content": "string",
  "openid": "string",
  "page": "string",
  "type": "string"
}

###
GET http://localhost/api/feedback/csv

